[defaults]
shell = "/usr/bin/fish"

[git]
name = "Opencode"
email = "me+opencode@sent-hil.com"

[shell]
init = [
    "direnv allow && eval \"$(direnv export bash)\""
]

[files]
mounts = [
    ".envrc:/workspaces/agent-sandbox/.envrc",
    "opencode.json:/workspaces/agent-sandbox/opencode.json"
]
